# Generated by Django 3.0.5 on 2020-04-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='description',
            field=models.CharField(default='this is desriptive of the shop', max_length=100),
        ),
        migrations.AddField(
            model_name='shop',
            name='shoptype',
            field=models.CharField(default='workshop', max_length=100),
        ),
    ]
